name: 🚀 Deploy FastAPI App to Linux Server

on:
  push:
    branches:
      - main  # Trigger only when main branch is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python (for FastAPI apps)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t fastapi-app:latest .

      # 4️⃣ Test the app (optional, can be skipped)
      - name: Run Unit Tests
        run: |
          echo "✅ Running Tests..."
          python -m unittest discover -s tests || echo "No tests found."

      # 5️⃣ Deploy to Linux Server via SSH
      - name: Deploy to Linux Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/fastapi-app
            git pull origin main
            docker-compose down
            docker-compose up -d --build
